version: "3.8"

services:
  mysql:  
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: "hydraweb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "recast203"
      MYSQL_ROOT_PASSWORD: "recast203"
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mysql_db_vol:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  influxdb:
    image: influxdb
    environment:
      INFLUXDB_HOSTNAME: hydraweb.influxdbhost.com
      INFLUXDB_ADMIN_USER: root
      INFLUXDB_ADMIN_PASSWORD: 12345678
    volumes:
      - /var/lib/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"

  influxdb_cli:
    links:
      - influxdb
    image: quay.io/influxdb/influxdb:v2.0.3
# Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
    entrypoint: influx setup --bucket mybucket -t mytoken -o myorg --username=myusername --password=passwordpasswordpassword --host=http://influxdb:8086 -f
      # Wait for the influxd service in the influxdb container has fully bootstrapped before trying to setup an influxdb instance with the influxdb_cli service. 
    restart: on-failure:10
    depends_on:
      - influxdb

  client:
    build: ./client 
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/client
      - node-modules:/app/client/node_modules
    ports:
      - "3000:3000"

  server:
    build: ./server
    command:  >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/server

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      CERTBOT_EMAIL: "00857211@mail.ntou.edu.tw"
    volumes:
      - ./log:/var/log/nginx
      - nginx_secrets:/etc/letsencrypt
    depends_on:
      - server

volumes:
  mysql_db_vol:
  nginx_secrets:
  node-modules: